%macro liblist_dorm;
libname srv_wrk "E:\Dropbox\WRDS\server_work";
libname a_index "E:\Dropbox\WRDS\CRSP\sasdata\a_indexes";
libname a_stock "E:\Dropbox\WRDS\CRSP\sasdata\a_stock";
libname a_ccm "E:\Dropbox\WRDS\CRSP\sasdata\a_ccm";
libname a_treas "E:\Dropbox\WRDS\CRSP\sasdata\a_treasuries";
libname comp "E:\Dropbox\WRDS\comp\sasdata\naa";
libname ff "E:\Dropbox\WRDS\ff\sasdata";
libname frb "E:\Dropbox\WRDS\frb\sasdata";
libname mysas "E:\Dropbox\WRDS\CRSP\mysas";
libname myOption "E:\Dropbox\WRDS\CRSP\myOption";
libname myMacro "E:\Dropbox\GitHub\CRSP_local\myMacro";
libname optionm "E:\optionm\sasdata";
libname BEM "E:\Dropbox\GitHub\CRSP_local\Bali, Engle, Murray - replications";
libname ff_repl "E:\Dropbox\WRDS\CRSP\ff_repl";
libname VIX "E:\Dropbox\WRDS\cboe\sasdata";
libname myVIX "E:\Dropbox\WRDS\CRSP\myVIX";
libname OpFull "E:\Dropbox\WRDS\CRSP\myOption_full";
libname HighMmt "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\HigherMoments\data";
libname TRP "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\TRP\data";
libname XSREG "E:\Dropbox\WRDS\XSREG\sasdata";
libname ambig "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\ambiguity_premium\data";
libname AHXZ "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\AHXZ_2006\data";
libname Barras "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\Barras_Malkhozov_2016\data";
libname FF92 "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\FF_92\data";
libname myModule "E:\Dropbox\GitHub\CRSP_local\myModule";
libname ibes "E:\Dropbox\WRDS\ibes\sasdata";
libname BBT "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\BBT_2017\data";
libname BBG "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\BBG_2018\data";
libname HW17 "E:\Dropbox\GitHub\CRSP_local\Codes - Papers\HW_2017\sasdata";

%mend liblist_dorm;
