/* ************************************************************************* */
/* ************** W R D S   R E S E A R C H   A P P L I C A T I O N S ****** */
/* ************************************************************************* */
/* Program  : taq_date_range.sas                                             */
/* Date     : Modified Aug, 2011                                             */
/* Author   : Mark Keintz                                                    */
/* ***************************************************************************/

** Different than the taq_basic sample program, this program provides the
ability to create taq sample data from beggining and ending dates that are
in the middle of the month **;
** This is done by the macro "taq_daily_dataset"; 
** See note in taq_basic on why and when OPEN=DEFER is usefull **;

%macro taq_daily_dataset_list(type=ct,begyyyymmdd=,endyyyymmdd=) / des="Autogenerated list of needed Daily TAQ datasets";
	%let type=%lowcase(&type);
	/* Get SAS date values for date range endpoints */
	%let begdate = %sysfunc(inputn(&begyyyymmdd,yymmdd8.));
	%let enddate = %sysfunc(inputn(&endyyyymmdd,yymmdd8.));
		%do d=&begdate %to &enddate /** For each date in the DATE range */;
			%let yyyymmdd=%sysfunc(putn(&d,yymmddn8.));
			/*If the corresponding dataset exists, add it to the list */
			%if %sysfunc(exist(taq.&type._&yyyymmdd)) %then taq.&type._&yyyymmdd;
		%end;
%mend;


* using this macro;
data my_output;
  set %taq_daily_dataset_list(type=ct,begyyyymmdd=19931210,endyyyymmdd=19940214) open=defer;
  where symbol in ("MSFT","IBM","DELL");
  if time >= "9:40:00"t and time <= "10:15:00"t;
run;

/* ********************************************************************************* */
/* *************  Material Copyright Wharton Research Data Services  *************** */
/* ****************************** All Rights Reserved ****************************** */
/* ********************************************************************************* */

